# https://circleci.com/docs/2.0/language-javascript/
version: 2.1
jobs:
  node-16:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run cov:send
      - persist_to_workspace:
          root: .
          paths:
            - 'build'

  publish:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - run: node tools/set_version.js
      - run: npm publish --dry-run

  node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run cov:send

workflows:
  build:
    jobs:
      - node-16
      - node-latest
      - publish:
          filters:
            tags:
              only:
                - /v\d+\.\d+\.\d+/
          requires:
            - node-16
